# -*- coding: utf-8 -*-
"""complaint_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BAV_nTfDQbeMokl2WuNYCFw3Hoxe1s7N
"""

import os
import sqlite3
import pandas as pd
from typing import Dict, Any, List

# Imports from your upstream agent ecosystem
try:
    from resource_monitoring_agent import DB_PATH as RESOURCE_DB_PATH, build_database
except ImportError:
    RESOURCE_DB_PATH = "resource_simulation.db"
    build_database = None

try:
    from weather_agent import ConstructionWeatherAgent
except ImportError:
    ConstructionWeatherAgent = None


class DynamicComplaintAgent:
    def __init__(self):
        self.agent_name = "Dynamic-Site-Complaint-Agent"

        # Costing & schedule rate parameters (aligned with Cost Agent)
        self.HOURLY_LABOR_RATE = 150.0          # ₹150 / worker / hour
        self.HOURLY_SITE_OVERHEAD = 1875.0      # ₹15,000 / 8-hour day = ₹1,875/hr
        self.EQUIPMENT_HOURLY_STANDBY = 500.0   # ₹500 / unit / hour

    # --------------------------------------------------------------------------
    # 1. DYNAMIC ZONE DATA RETRIEVAL (RESOURCE AGENT)
    # --------------------------------------------------------------------------
    def _fetch_live_zone_resources(self, zone: str) -> Dict[str, Any]:
        """Queries the live SQLite database created by resource_monitoring_agent.py"""
        labour_count = 0
        material_shortage = 0
        equipment_under_maint = 0

        if os.path.exists(RESOURCE_DB_PATH):
            try:
                conn = sqlite3.connect(RESOURCE_DB_PATH)
                labour_df = pd.read_sql("SELECT * FROM labour WHERE Zone = ?", conn, params=(zone,))
                material_df = pd.read_sql("SELECT * FROM material WHERE Zone = ?", conn, params=(zone,))
                equipment_df = pd.read_sql("SELECT * FROM equipment WHERE Zone = ?", conn, params=(zone,))
                conn.close()

                if not labour_df.empty:
                    labour_count = int(labour_df["Available_Labour"].sum())
                if not material_df.empty:
                    shortage = material_df["Required_Quantity"].sum() - material_df["Available_Quantity"].sum()
                    material_shortage = max(0, int(shortage))
                if not equipment_df.empty:
                    equipment_under_maint = int(equipment_df["Under_Maintenance"].sum())
            except Exception:
                pass

        # Smart fallbacks if DB is offline or zone not found
        zone_defaults = {
            "Zone A": {"workers": 12, "shortage": 30, "maint": 1},
            "Zone B": {"workers": 15, "shortage": 40, "maint": 2},
            "Zone C": {"workers": 8,  "shortage": 50, "maint": 0},
            "Zone D": {"workers": 10, "shortage": 25, "maint": 1},
        }
        defaults = zone_defaults.get(zone, {"workers": 6, "shortage": 20, "maint": 0})

        return {
            "workers": labour_count if labour_count > 0 else defaults["workers"],
            "material_shortage": material_shortage if material_shortage > 0 else defaults["shortage"],
            "equipment_maint": equipment_under_maint if equipment_under_maint > 0 else defaults["maint"],
        }

    # --------------------------------------------------------------------------
    # 2. DYNAMIC WEATHER RISK CHECK (WEATHER AGENT)
    # --------------------------------------------------------------------------
    def _check_weather_risk(self) -> Dict[str, Any]:
        """Checks if bad weather exacerbates the delay"""
        if ConstructionWeatherAgent is not None:
            try:
                w_agent = ConstructionWeatherAgent()
                report = w_agent.analyze_site_risks()
                return {
                    "is_adverse": report.get("status") in ["CRITICAL", "MODERATE"],
                    "wind": report.get("wind", 0),
                    "rain_prob": report.get("rain_prob", 0)
                }
            except Exception:
                pass
        return {"is_adverse": False, "wind": 15, "rain_prob": 10}

    # --------------------------------------------------------------------------
    # 3. DYNAMIC REASONING ENGINE (SCHEDULE, COST, ROOT CAUSE, ACTIONS)
    # --------------------------------------------------------------------------
    def process_complaint(
        self,
        complaint_id: str,
        category: str,
        location: str,
        severity: str,
        complaint: str,
    ) -> Dict[str, Any]:
        """Dynamically calculates root cause, impacts, affected workers, and cost."""

        category_clean = category.strip().lower()
        complaint_clean = complaint.strip().lower()
        severity_clean = severity.strip().upper()

        # 1. Fetch live zone conditions from Resource Agent
        zone_data = self._fetch_live_zone_resources(location)
        weather = self._check_weather_risk()

        # ----------------------------------------------------------------------
        # A. DYNAMIC AFFECTED WORKERS CALCULATION
        # ----------------------------------------------------------------------
        base_workers = zone_data["workers"]
        if severity_clean == "CRITICAL":
            affected_workers = base_workers                       # 100% of zone crew halted
        elif severity_clean == "HIGH":
            affected_workers = max(1, int(base_workers * 0.75))   # 75% affected
        elif severity_clean == "MEDIUM":
            affected_workers = max(1, int(base_workers * 0.40))   # 40% affected
        else: # LOW
            affected_workers = max(1, int(base_workers * 0.20))   # 20% affected

        # ----------------------------------------------------------------------
        # B. DYNAMIC ROOT CAUSE DETERMINATION
        # ----------------------------------------------------------------------
        shortage_qty = zone_data["material_shortage"]

        if "glove" in complaint_clean or "ppe" in complaint_clean or "helmet" in complaint_clean or "vest" in complaint_clean:
            root_cause = "PPE inventory shortage."
            item_name = "gloves" if "glove" in complaint_clean else "PPE kits"
        elif "equipment" in complaint_clean or "machine" in complaint_clean or "crane" in complaint_clean or "excavator" in complaint_clean:
            root_cause = f"Equipment breakdown and unplanned maintenance ({zone_data['equipment_maint']} unit(s) down)."
            item_name = "machinery parts"
        elif "material" in complaint_clean or "cement" in complaint_clean or "steel" in complaint_clean or "rebar" in complaint_clean:
            root_cause = f"Supply chain delivery delay in {location} ({shortage_qty} units deficit)."
            item_name = "raw materials"
        elif "weld" in complaint_clean or "crack" in complaint_clean or "defect" in complaint_clean or "quality" in complaint_clean:
            root_cause = "Non-conformance workmanship defect requiring structural remediation."
            item_name = "remediation materials"
        elif "noise" in complaint_clean or "dust" in complaint_clean or "environment" in complaint_clean:
            root_cause = "Environmental mitigation threshold exceedance."
            item_name = "dust barriers / acoustic curtains"
        else:
            root_cause = f"Operational workflow bottleneck identified in {location}."
            item_name = "supplies"

        # ----------------------------------------------------------------------
        # C. DYNAMIC SCHEDULE IMPACT CALCULATION
        # ----------------------------------------------------------------------
        if severity_clean == "CRITICAL":
            delay_hours = 8
        elif severity_clean == "HIGH":
            delay_hours = 2 if "ppe" in category_clean or "safety" in category_clean else 4
        elif severity_clean == "MEDIUM":
            delay_hours = 1
        else: # LOW
            delay_hours = 0.5

        # If weather is also bad, compound the delay dynamically
        if weather["is_adverse"]:
            delay_hours += 1.5

        # Format schedule impact string
        if delay_hours >= 8:
            days = delay_hours / 8.0
            schedule_impact_str = f"{days:.1f} day{'s' if days > 1 else ''}"
        else:
            schedule_impact_str = f"{int(delay_hours) if delay_hours.is_integer() else delay_hours} hours"

        # ----------------------------------------------------------------------
        # D. DYNAMIC COST IMPACT CALCULATION
        # Formula: (Idle Worker Cost) + (Site Overhead) + (Procurement / Rectification)
        # ----------------------------------------------------------------------
        idle_labor_cost = affected_workers * delay_hours * self.HOURLY_LABOR_RATE
        site_overhead_cost = delay_hours * self.HOURLY_SITE_OVERHEAD

        # Material / Procurement / Rectification Cost based on category & severity
        if "ppe" in category_clean or "safety" in category_clean:
            procurement_cost = shortage_qty * 350.0   # ₹350 per safety unit/pair
        elif "equipment" in category_clean:
            procurement_cost = 25000.0 * (1 if severity_clean != "CRITICAL" else 2)
        elif "quality" in category_clean:
            procurement_cost = 45000.0
        else:
            procurement_cost = shortage_qty * 500.0

        total_cost = idle_labor_cost + site_overhead_cost + procurement_cost

        # Round to nearest 500 for clean reporting
        rounded_cost = int(round(total_cost / 500.0) * 500)

        # ----------------------------------------------------------------------
        # E. DYNAMIC RECOMMENDED ACTIONS
        # ----------------------------------------------------------------------
        recommended_actions = []

        if severity_clean in ["CRITICAL", "HIGH"]:
            recommended_actions.append("Stop affected activity.")
        else:
            recommended_actions.append("Isolate impacted work section.")

        if "ppe" in category_clean or "safety" in category_clean or "glove" in complaint_clean:
            recommended_actions.append(f"Procure {shortage_qty} pairs of {item_name}.")
            recommended_actions.append("Distribute PPE to workers.")
            recommended_actions.append("Verify compliance using Safety Agent.")
        elif "equipment" in category_clean or "machine" in complaint_clean:
            recommended_actions.append(f"Dispatch mobile technician to inspect machinery in {location}.")
            recommended_actions.append("Reroute standby excavator/equipment from adjacent zone.")
            recommended_actions.append("Notify Plant & Machinery (CPM) insurance broker.")
        elif "quality" in category_clean or "defect" in complaint_clean:
            recommended_actions.append("Issue Stop-Work Notice and log formal Non-Conformance Report (NCR).")
            recommended_actions.append("Perform ultrasonic / non-destructive testing re-scan.")
            recommended_actions.append("Execute structural rectification procedure.")
        else:
            recommended_actions.append(f"Expedite delivery of {item_name} to {location}.")
            recommended_actions.append("Reallocate idle workforce to non-dependent tasks.")
            recommended_actions.append("Update Schedule Agent baseline to reflect revised turnaround.")

        return {
            "complaint_id": complaint_id,
            "category": category,
            "location": location,
            "severity": severity,
            "complaint": complaint,
            "root_cause": root_cause,
            "affected_workers": affected_workers,
            "safety_impact": severity.upper(),
            "schedule_impact": schedule_impact_str,
            "estimated_cost_impact": f"₹{rounded_cost:,}",
            "recommended_actions": recommended_actions,
            "status": "OPEN",
        }

    # --------------------------------------------------------------------------
    # 4. DISPLAY FORMATTER
    # --------------------------------------------------------------------------
    def display_report(self, report: Dict[str, Any]):
        print(f"COMPLAINT ID: {report['complaint_id']}\n")
        print(f"Category: {report['category']}")
        print(f"Location: {report['location']}")
        print(f"Severity: {report['severity']}\n")
        print("Complaint:")
        print(f"{report['complaint']}\n")
        print("Root Cause:")
        print(f"{report['root_cause']}\n")
        print(f"Affected Workers: {report['affected_workers']}\n")
        print(f"Safety Impact: {report['safety_impact']}")
        print(f"Schedule Impact: {report['schedule_impact']}")
        print(f"Estimated Cost Impact: {report['estimated_cost_impact']}\n")
        print("Recommended Action:")
        for idx, action in enumerate(report["recommended_actions"], 1):
            print(f"{idx}. {action}")
        print(f"\nStatus: {report['status']}")
        print("-" * 60)


# --------------------------------------------------------------------------
# 5. DEMO: DEMONSTRATING VARYING OUTPUTS BASED ON DIFFERENT INPUTS
# --------------------------------------------------------------------------
if __name__ == "__main__":
    agent = DynamicComplaintAgent()

    # TEST CASE 1: Your original Safety / Gloves complaint in Zone C
    test_1 = agent.process_complaint(
        complaint_id="CMP-1025",
        category="PPE/Safety",
        location="Zone C",
        severity="HIGH",
        complaint="Safety gloves unavailable for workers."
    )
    print("=== TEST CASE 1: SAFETY / GLOVES SHORTAGE (Zone C) ===")
    agent.display_report(test_1)

    # TEST CASE 2: Equipment Breakdown in Zone A with CRITICAL severity
    test_2 = agent.process_complaint(
        complaint_id="CMP-1026",
        category="Equipment",
        location="Zone A",
        severity="CRITICAL",
        complaint="Tower crane hydraulic pressure failure halting all moment frame lifts."
    )
    print("=== TEST CASE 2: CRANE BREAKDOWN (Zone A, CRITICAL) ===")
    agent.display_report(test_2)

    # TEST CASE 3: Quality Defect in Zone B with MEDIUM severity
    test_3 = agent.process_complaint(
        complaint_id="CMP-1027",
        category="Quality",
        location="Zone B",
        severity="MEDIUM",
        complaint="Honeycombing and voids detected on concrete shear wall after formwork removal."
    )
    print("=== TEST CASE 3: QUALITY DEFECT (Zone B, MEDIUM) ===")
    agent.display_report(test_3)